### ISSUE TITLE
El número de sesiones en el popup de creación de turno de la Agenda aparece cargado con un número incorrecto luego de haber creado un turno

### ISSUE THREAD

**Issue by Nachin31** [FDMilesi/pfc-gmz#18]
1 - Seleccionar un lugar libre en la agenda para crear un nuevo turno.
2 - Seleccionar un paciente existente que tenga algun tratamiento ya creado y con sesiones cargadas.

> > Hasta este punto, el número de sesiones en el titulo del popup es 1.
> > 3 - Seleccionar el tratamiento que ya posee X sesiones.
> > El título ya se actualizará a X + 1.
> > 4 - Guardar la sesión.
> > 5 - Ahora, tocar para crear una nueva sesión.
> > El paciente ya esta cargado.
> > 6 - Seleccionar el mismo tratamiento que en el paso 3.
> > El número de sesión ahora se incrementará a X+2.
> > 7 - Cancelar la carga de la sesión.
> > 8 - Seleccionar la sesión guardada en el paso 4, y eliminarla.
> > 9 - Seleccionar una celda vacía para crear una nueva sesión.
> > Aun se mantiene el mismo usuario; sin embargo el número de la sesión que se mantiene en el encabezado es incorrecto.

Tal vez lo mejor es cargar el número del encabezado sólo al seleccionar tratamiento; de esta forma, siempre que abramos el popup de creación de sesión estará vacío.

**Comment by fzen2016** [comment]
Solucionado.
