### ISSUE TITLE
No debería poder accederse al popup de repetición de sesiones si el tratamiento ya tiene todas sus sesiones asignadas

### ISSUE THREAD

**Issue by Nachin31** [FDMilesi/pfc-gmz#19]
Cuando un tratamiento tiene todas las sesiones asignadas a turnos, mostramos un popup de error al querer crearle una nueva sesión.

Sin embargo, no  hay restricción al tocar el botón de repetir sesión.
En este caso hay dos opciones:
1) Mostrar el mismo popup de error que se muestra cuando queremos crear la sesion individualmente.
2) Deshabilitar el botón de repetir sesión.

Por consistencia, tal vez la primer oopción es la mejor.

**Comment by fzen2016** [comment]
Al querer realizar la carga masiva, es decir cuando seleccionamos el botón de repetir sesión y después le damos guardar, se muestra el siguiente popup de error: "No se pueden agregar sesiones. El tratamiento posee un tope de X sesiones".
