### ISSUE TITLE
Se pueden crear turnos en horarios pasados

### ISSUE THREAD

**Issue by Nachin31** [FDMilesi/pfc-gmz#20]
Por ejemplo, puedo crear turnos a la mañana siendo que ya es la tarde.

Cuando queremos crear un turno en una fecha pasada, aparece una advertencia.
Lo mismo debería suceder si se crea una sesión en un horario pasado.

**Comment by fzen2016** [comment]
Se decidió dejar el mensaje "La sesión se creará en una fecha u hora anterior a la actual".
