### ISSUE TITLE
No se puede eliminar un tratamiento con estudios adjuntados.

### ISSUE THREAD

**Issue by fzen2016** [FDMilesi/pfc-gmz#29]
Se deberían eliminar en cascada todos los estudios asociados a este tratamiento.

**Comment by Nachin31** [comment]
Intente reproducirlo pero no pude; el tratamiento con estudios adjuntos se eliminaba sin problemas, y los estudios se borraban de la base también. Agregué un método para borrar los archivos del sistema de archivos, porque eso sí no se hacía (el trtamiento y los estudios desaparecían de la base, pero los archivos quedaban en el sistema).
