### ISSUE TITLE
El sistema muestra la tabla y deja agregar ordenes méddicas a un tratamiento de tipo Particular

### ISSUE THREAD

**Issue by Nachin31** [FDMilesi/pfc-gmz#9]

**Comment by fzen2016** [comment]
Además en el listado de tratamientos del paciente, este tratamiento "Particular" se muestra como No particular.

**Comment by FDMilesi** [comment]
El error concreto está en que un tipo de tratamiento que SIEMPRE debe ser particular, como gimnasia o estética, es creado como NO particular. Por eso deja agregar órdenes. Si el tratamiento es particular el sistema funciona correctamente no dejando agregar ordenes ni motrando la tabla de las mismas
